module.exports = {
  deer: [
    {
      name: "A (North 160 and South 110)",
      archery: "July 9,2022 - July 31,2022",
      general: "August 13,2022 - September 25,2022",
      tagQuota: "65,000",
      tagValid: "Tag is valid for zones A North 160 and South 110",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "B-1",
      archery: "August 20,2022 - September 11,2022",
      general: "September 17,2022 - October 23,2022",
      tagQuota: "35,000 total tags for B-1,B-2,B-3,B-4,B-5,B-6 combined",
      tagValid: "Tag is valid for all B zones for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },

    {
      name: "B-2",
      archery: "August 20,2022 - September 11,2022",
      general: "September 17,2022 - October 23,2022",
      tagQuota: "35,000 total tags for B-1,B-2,B-3,B-4,B-5,B-6 combined",
      tagValid: "Tag is valid for all B zones for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "B-3",
      archery: "August 20,2022 - September 11,2022",
      general: "September 17,2022 - October 23,2022",
      tagQuota: "35,000 total tags for B-1,B-2,B-3,B-4,B-5,B-6 combined",
      tagValid: "Tag is valid for all B zones for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "B-4",
      archery: "July 23,2022 - August 14,2022",
      general: "August 27,2022 - October 2,2022",
      tagQuota: "35,000 total tags for B-1,B-2,B-3,B-4,B-5,B-6 combined",
      tagValid: "Tag is valid for all B zones for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "B-5",
      archery: "August 20,2022 - September 11,2022",
      general: "September 17,2022 - October 23,2022",
      tagQuota: "35,000 total tags for B-1,B-2,B-3,B-4,B-5,B-6 combined",
      tagValid: "Tag is valid for all B zones for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "B-6",
      archery: "August 20,2022 - September 11,2022",
      general: "September 17,2022 - October 16,2022",
      tagQuota: "35,000 total tags for B-1,B-2,B-3,B-4,B-5,B-6 combined",
      tagValid: "Tag is valid for all B zones for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "C-1",
      archery: "See hunt zone A-1",
      general: "September 17,2022 - October 16,2022",
      tagQuota: "8,150 total tags for C-1,C-2,C-3,C-4 combined",
      tagValid:
        "Tag is valid for all C zones for general season only(archery season see zone A-1)",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "C-2",
      archery: "See hunt zone A-1",
      general: "September 17,2022 - October 23,2022",
      tagQuota: "8,150 total tags for C-1,C-2,C-3,C-4 combined",
      tagValid:
        "Tag is valid for all C zones for general season only(archery season see zone A-1)",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "C-3",
      archery: "See hunt zone A-1",
      general: "September 17,2022 - October 23,2022",
      tagQuota: "8,150 total tags for C-1,C-2,C-3,C-4 combined",
      tagValid:
        "Tag is valid for all C zones for general season only(archery season see zone A-1)",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "C-4",
      archery: "See hunt zone A-1",
      general: "September 17,2022 - October 2,2022",
      tagQuota: "8,150 total tags for C-1,C-2,C-3,C-4 combined",
      tagValid:
        "Tag is valid for all C zones for general season only(archery season see zone A-1)",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-3",
      archery: "August 20,2022 - September 11,2022",
      general: "September 24,2022 - October 30,2022",
      tagQuota: "33,000 total tags for D-3,D-4,D-5 combined",
      tagValid:
        "Tag is valid for zones D-3,D-4,D-5 for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-4",
      archery: "August 20,2022 - September 11,2022",
      general: "September 24,2022 - October 30,2022",
      tagQuota: "33,000 total tags for D-3,D-4,D-5 combined",
      tagValid:
        "Tag is valid for zones D-3,D-4,D-5 for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-5",
      archery: "August 20,2022 - September 11,2022",
      general: "September 24,2022 - October 30,2022",
      tagQuota: "33,000 total tags for D-3,D-4,D-5 combined",
      tagValid:
        "Tag is valid for zones D-3,D-4,D-5 for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-6",
      archery: "August 20,2022 - September 11,2022",
      general: "September 17,2022 - October 30,2022",
      tagQuota: "10,000",
      tagValid:
        "Tag is valid for zone D-6 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-7",
      archery: "August 20,2022 - September 11,2022",
      general: "September 17,2022 - October 30,2022",
      tagQuota: "9,000",
      tagValid:
        "Tag is valid for zone D-7 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-8",
      archery: "August 20,2022 - September 11,2022",
      general: "September 24,2022 - October 23,2022",
      tagQuota: "8,000",
      tagValid:
        "Tag is valid for zone D-8 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-9",
      archery: "August 20,2022 - September 11,2022",
      general: "September 24,2022 - October 23,2022",
      tagQuota: "2,000",
      tagValid:
        "Tag is valid for zone D-9 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-10",
      archery: "August 20,2022 - September 11,2022",
      general: "September 24,2022 - October 23,2022",
      tagQuota: "700",
      tagValid:
        "Tag is valid for zone D-10 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-11",
      archery: "September 3,2022 - September 25,2022",
      general: "October 8,2022 - November 6,2022",
      tagQuota: "5,500",
      tagValid:
        "Tag is valid for zones D-11,D-13,D-15 for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-12",
      archery: "October 1,2022 - October 23,2022",
      general: "November 5,2022 - November 27,2022",
      tagQuota: "950",
      tagValid:
        "Tag is valid for zone D-12 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-13",
      archery: "September 3,2022 - September 25,2022",
      general: "October 8,2022 - November 6,2022",
      tagQuota: "4,000",
      tagValid:
        "Tag is valid for zones D-11,D-13,D-15 for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-14",
      archery: "September 3,2022 - September 25,2022",
      general: "October 8,2022 - November 6,2022",
      tagQuota: "3,000",
      tagValid:
        "Tag is valid for zone D-14 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-15",
      archery: "September 3,2022 - September 25,2022",
      general: "October 8,2022 - November 6,2022",
      tagQuota: "1,500",
      tagValid:
        "Tag is valid for zones D-11,D-13,D-15 for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-16",
      archery: "September 3,2022 - September 25,2022",
      general: "October 22,2022 - November 20,2022",
      tagQuota: "3,000",
      tagValid:
        "Tag is valid for zone D-16 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-17",
      archery: "September 3,2022 - September 25,2022",
      general: "October 8,2022 - October 30,2022",
      tagQuota: "500",
      tagValid:
        "Tag is valid for zone D-17 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "D-19",
      archery: "September 3,2022 - September 25,2022",
      general: "October 1,2022 - October 30,2022",
      tagQuota: "1,500",
      tagValid:
        "Tag is valid for zone D-19 only, for archery and general seasons",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-1",
      archery: "See hunt zone A-3",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "760",
      tagValid: "Tag is valid for zone X-1 only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-2",
      archery: "See hunt zone A-4",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "190",
      tagValid: "Tag is valid for zone X-2 only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-3a",
      archery: "See hunt zone A-5",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "355",
      tagValid: "Tag is valid for zone X-3a only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-3b",
      archery: "See hunt zone A-6",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "500",
      tagValid: "Tag is valid for zone X-3b only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-4",
      archery: "See hunt zone A-7",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "480",
      tagValid: "Tag is valid for zone X-4 only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-5a",
      archery: "See hunt zone A-8",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "75",
      tagValid: "Tag is valid for zone X-5a only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-5b",
      archery: "See hunt zone A-9",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "50",
      tagValid: "Tag is valid for zone X-5b only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-6a",
      archery: "See hunt zone A-11",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "330",
      tagValid: "Tag is valid for zone X-6a only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-6b",
      archery: "See hunt zone A-12",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "310",
      tagValid: "Tag is valid for zone X-6b only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-7a",
      archery: "See hunt zone A-13",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "230",
      tagValid: "Tag is valid for zone X-7a only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-7b",
      archery: "See hunt zone A-14",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "135",
      tagValid: "Tag is valid for zone X-7b only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-8",
      archery: "See hunt zone A-15",
      general: "September 24,2022 - October 9,2022",
      tagQuota: "210",
      tagValid: "Tag is valid for zone X-8 only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-9a",
      archery: "See hunt zone A-16",
      general: "September 17,2022 - October 10,2022",
      tagQuota: "270",
      tagValid: "Tag is valid for zone X-9a only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-9b",
      archery: "See hunt zone A-17",
      general: "September 17,2022 - October 10,2022",
      tagQuota: "230",
      tagValid: "Tag is valid for zone X-9b only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-9c",
      archery: "See hunt zone A-18",
      general: "October 15,2022 - November 6,2022",
      tagQuota: "325",
      tagValid: "Tag is valid for zone X-9c only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-10",
      archery: "See hunt zone A-19",
      general: "September 24,2022 - October 9,2022",
      tagQuota: "400",
      tagValid: "Tag is valid for zone X-10 only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "X-12",
      archery: "See hunt zone A-20",
      general: "September 17,2022 - October 10,2022",
      tagQuota: "350",
      tagValid: "Tag is valid for zone X-12 only and only for general season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-1 (aka C-1)",
      archery: "August 20,2022 - September 4,2022",
      general: "See hunt zone C-1",
      tagQuota:
        "1,945 tags total between A-1(aka C-1),A-1(aka C-2),A-1(aka C-3),A-1(aka C-4)",
      tagValid:
        "Tag is valid for all of zone A-1(aka C-1,C-2,C-3,C-4) only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-1 (aka C-2)",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone C-2",
      tagQuota:
        "1,945 tags total between A-1(aka C-1),A-1(aka C-2),A-1(aka C-3),A-1(aka C-4)",
      tagValid:
        "Tag is valid for all of zone A-1(aka C-1,C-2,C-3,C-4) only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-1 (aka C-3)",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone C-3",
      tagQuota:
        "1,945 tags total between A-1(aka C-1),A-1(aka C-2),A-1(aka C-3),A-1(aka C-4)",
      tagValid:
        "Tag is valid for all of zone A-1(aka C-1,C-2,C-3,C-4) only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-1 (aka C-4)",
      archery: "August 20,2022 - September 4,2022",
      general: "See hunt zone C-4",
      tagQuota:
        "1,945 tags total between A-1(aka C-1),A-1(aka C-2),A-1(aka C-3),A-1(aka C-4)",
      tagValid:
        "Tag is valid for all of zone A-1(aka C-1,C-2,C-3,C-4) only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-3",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-1",
      tagQuota: "100",
      tagValid: "Tag is valid for zone A-3 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-4",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-2",
      tagQuota: "10",
      tagValid: "Tag is valid for zone A-4 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-5",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-3a",
      tagQuota: "40",
      tagValid: "Tag is valid for zone A-5 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-6",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-3b",
      tagQuota: "70",
      tagValid: "Tag is valid for zone A-6 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-7",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-4",
      tagQuota: "120",
      tagValid: "Tag is valid for zone A-7 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-8",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-5a",
      tagQuota: "10",
      tagValid: "Tag is valid for zone A-8 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-9",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-5b",
      tagQuota: "5",
      tagValid: "Tag is valid for zone A-9 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-11",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-2",
      tagQuota: "50",
      tagValid: "Tag is valid for zone A-11 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-12",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-6b",
      tagQuota: "90",
      tagValid: "Tag is valid for zone A-12 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-13",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-7a",
      tagQuota: "45",
      tagValid: "Tag is valid for zone A-13 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-14",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-7b",
      tagQuota: "25",
      tagValid: "Tag is valid for zone A-14 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-15",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-8",
      tagQuota: "40",
      tagValid: "Tag is valid for zone A-15 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-16",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-9a",
      tagQuota: "30",
      tagValid: "Tag is valid for zone A-16 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-17",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-9b",
      tagQuota: "210",
      tagValid: "Tag is valid for zone A-17 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-18",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-9c",
      tagQuota: "350",
      tagValid: "Tag is valid for zone A-18 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-19",
      archery: "August 20,2022 - September 4,2022",
      general: "See hunt zone X-10",
      tagQuota: "100",
      tagValid: "Tag is valid for zone A-19 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-20",
      archery: "August 20,2022 - September 11,2022",
      general: "See hunt zone X-12",
      tagQuota: "40",
      tagValid: "Tag is valid for zone A-20 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-21 Anderson Flat Archery Buck Hunt",
      archery: "November 12,2022 - November 25,2022",
      general: "",
      tagQuota: "25",
      tagValid: "Tag is valid for zone A-21 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-22 San Diego Archery Either-Sex Deer Hunt (Split Season)",
      archery: "September 3,2022 - October 16,2022",
      archery: "November 19,2022 - December 31,2022",
      general: "",
      tagQuota: "1,000",
      tagValid: "Tag is valid for zone A-22 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-24 Monterey Archery Either-Sex Deer Hunt",
      archery: "October 8,2022 - November 6,2022",
      general: "",
      tagQuota: "100",
      tagValid: "Tag is valid for zone A-24 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-25 Lake Sonoma Archery Either-Sex Deer Hunt",
      archery: "October 1,2022 - October 24,2022",
      general: "",
      tagQuota: "35",
      tagValid: "Tag is valid for zone A-25 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-26 Bass Hill Archery Buck Hunt",
      archery: "November 19,2022 - December 11,2022",
      general: "",
      tagQuota: "30",
      tagValid: "Tag is valid for zone A-26 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-27 Devil's Garden Archery Buck Hunt",
      archery: "October 22,2022 - November 6,2022",
      general: "",
      tagQuota: "10",
      tagValid: "Tag is valid for zone A-27 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-30 Covelo Archery Buck Hunt",
      archery: "November 12,2022 - November 27,2022",
      general: "",
      tagQuota: "40",
      tagValid: "Tag is valid for zone A-30 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-31 Los Angeles Archery Either-Sex Deer Hunt",
      archery: "September 24,2022 - December 31,2022",
      general: "",
      tagQuota: "1,000",
      tagValid: "Tag is valid for zone A-31 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-32 Ventura/Los Angeles Late Season Archery Either-Sex Deer Hunt",
      archery: "November 12,2022 - December 4,2022",
      general: "",
      tagQuota: "250",
      tagValid: "Tag is valid for zone A-32 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "A-33 Fort Hunter Liggett Late Season Archery Either-Sex Deer Hunt",
      archery: "October 1,2022 - November 11,2022",
      general: "",
      tagQuota: "50",
      tagValid: "Tag is valid for zone A-33 only and only for archery season",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "AO (Archery Only Tag)",
      archery: "Season depends on the zone you plan to hunt",
      general: "Season depends on the zone you plan to hunt",
      tagQuota: "Unlimited amount of tags",
      tagValid:
        "Tag is valid during archery and general seasons for zones A (North 160 and South 110), all B zones, all D zones, and G-10. Use of Archery equipment only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-1 Late Season Buck Hunt for Zone C-4",
      archery: "",
      general: "October 22,2022 - October 30,2022",
      tagQuota: "2,710",
      tagValid: "Tag is valid for zone G-1",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-3 Goodale Buck Hunt",
      archery: "",
      general: "December 3,2022 - December 18,2022",
      tagQuota: "25",
      tagValid: "Tag is valid for zone G-3",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-6 Kern River Deer Herd Buck Hunt",
      archery: "",
      general: "December 3,2022 - December 11,2022",
      tagQuota: "50",
      tagValid: "Tag is valid for zone G-6",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-7 Beale Either-Sex Deer Hunt (Military Only)",
      archery: "",
      general: "August 8,2022 - November 6,2022",
      tagQuota: "20 Military Only",
      tagValid: "Tag is valid for zone G-7",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-8 Fort Hunter Liggett Antlerless Deer Hunt (Military and Public)",
      archery: "",
      general: "October 1, 2, 8, 9, 10,2022",
      tagQuota: "20",
      tagValid: "Tag is valid for zone G-8",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-10 Camp Pendleton Either-Sex Deer Hunt (Military Only; Hunt Day Restrictions)",
      archery: "",
      general: "September 3,2022 - December 4,2022",
      tagQuota: "250 Military Only",
      tagValid: "Tag is valid for zone G-3",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-12 Gray Lodge Shotgun Either-Sex Deer Hunt",
      archery: "",
      general: "September 17,2022 - September 25,2022",
      tagQuota: "30",
      tagValid: "Tag is valid for zone G-12",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-13 San Diego Antlerless Deer Hunt",
      archery: "",
      general: "October 22,2022 - November 13,2022",
      tagQuota: "300",
      tagValid: "Tag is valid for zone G-13",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-19 Sutter-Yuba Wildlife Areas Either-Sex Deer Hunt",
      archery: "",
      general: "September 24,2022 - December 31,2022",
      tagQuota: "25",
      tagValid: "Tag is valid for zone G-19",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-21 Ventana Wilderness Buck Hunt",
      archery: "",
      general: "November 12,2022 - December 4,2022",
      tagQuota: "25",
      tagValid: "Tag is valid for zone G-21",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-37 Anderson Flat Buck Hunt",
      archery: "",
      general: "November 26,2022 - December 4,2022",
      tagQuota: "25",
      tagValid: "Tag is valid for zone G-37",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-38 X-10 Late Season Buck Hunt",
      archery: "",
      general: "October 15,2022 - October 30,2022",
      tagQuota: "300",
      tagValid: "Tag is valid for zone G-38",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "G-39 Round Valley Late Season Buck Hunt",
      archery: "",
      general: "October 22,2022 - November 6,2022",
      tagQuota: "2",
      tagValid: "Tag is valid for zone G-39",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "M-3 Doyle Muzzleloading Rifle Buck Hunt",
      archery: "",
      general: "November 19,2022 - November 27,2022",
      tagQuota: "20",
      tagValid: "Tag is valid for zone M-3 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "M-4 Horse Lake Muzzleloading Rifle Buck Hunt",
      archery: "",
      general: "October 22,2022 - October 30,2022",
      tagQuota: "10",
      tagValid: "Tag is valid for zone M-4 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "M-5 East Lassen Muzzleloading Rifle Buck Hunt",
      archery: "",
      general: "October 22,2022 - October 30,2022",
      tagQuota: "5",
      tagValid: "Tag is valid for zone M-5 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "M-6 San Diego Muzzleloading Rifle Either-Sex Deer Hunt",
      archery: "",
      general: "December 17,2022 - December 31,2022",
      tagQuota: "80",
      tagValid: "Tag is valid for zone M-6 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "M-7 Ventura Muzzleloading Rifle Either-Sex Deer Hunt",
      archery: "",
      general: "November 26,2022 - December 11,2022",
      tagQuota: "150",
      tagValid: "Tag is valid for zone M-7 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "M-8 Bass Hill Muzzleloading Rifle Buck Hunt",
      archery: "",
      general: "October 22,2022 - October 30,2022",
      tagQuota: "20",
      tagValid: "Tag is valid for zone M-8 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "M-9 Devil's Garden Muzzleloading Rifle Buck Hunt",
      archery: "",
      general: "October 22,2022 - November 6,2022",
      tagQuota: "15",
      tagValid: "Tag is valid for zone M-9 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "M-11 Northwestern California Muzzleloading Rifle Buck Hunt",
      archery: "",
      general: "November 12,2022 - November 27,2022",
      tagQuota: "20",
      tagValid: "Tag is valid for zone M-11 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "MA-1 San Luis Obispo Muzzleloading Rifle/Archery Either-Sex Deer Hunt",
      archery: "",
      general: "November 26,2022 - December 11,2022",
      tagQuota: "150",
      tagValid: "Tag is valid for zone MA-1 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "MA-3 Santa Barbara Muzzleloading Rifle/Archery Buck Hunt",
      archery: "",
      general: "November 26,2022 - December 11,2022",
      tagQuota: "150",
      tagValid: "Tag is valid for zone MA-3 only",
      requires: "Hunting license, Deer tag",
    },
    {
      name: "J-1 Lake Sonoma Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "November 5,2022 - November 6,2022",
      tagQuota: "25",
      tagValid: "Tag is valid for zone J-1 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-3 Tehama Wildlife Area Apprentice Buck Hunt",
      archery: "",
      general: "November 26,2022 - November 27,2022",
      tagQuota: "15",
      tagValid: "Tag is valid for zone J-3 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-4 Shasta-Trinity Apprentice Buck Hunt",
      archery: "",
      general: "November 26,2022 - December 4,2022",
      tagQuota: "15",
      tagValid: "Tag is valid for zone J-4 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-8 Daugherty Hill Wildlife Area Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "December 3,2022 - December 31,2022",
      tagQuota: "15",
      tagValid: "Tag is valid for zone J-8 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-9 Little Dry Creek Apprentice Shotgun Either-Sex Deer Hunt",
      archery: "",
      general: "September 17,2022 - September 25,2022",
      tagQuota: "5",
      tagValid: "Tag is valid for zone J-9 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-10 Fort Hunter Liggett Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "October 1, 2, 8, 9, 10,2022",
      tagQuota: "30",
      tagValid: "Tag is valid for zone J-10 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-11 San Bernardino Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "November 19,2022 - November 27,2022",
      tagQuota: "40",
      tagValid: "Tag is valid for zone J-11 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-12 Round Valley Apprentice Buck Hunt",
      archery: "",
      general: "December 3,2022 - December 18,2022",
      tagQuota: "10",
      tagValid: "Tag is valid for zone J-12 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-13 Los Angeles Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "November 19,2022 - November 27,2022",
      tagQuota: "40",
      tagValid: "Tag is valid for zone J-13 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-14 Riverside Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "November 19,2022 - November 27,2022",
      tagQuota: "30",
      tagValid: "Tag is valid for zone J-14 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-15 Anderson Flat Apprentice Buck Hunt",
      archery: "",
      general: "November 26,2022 - December 4,2022",
      tagQuota: "10",
      tagValid: "Tag is valid for zone J-15 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-16 Bucks Mountain/Nevada City Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "September 24,2022 - October 30,2022",
      tagQuota: "75",
      tagValid: "Tag is valid for zone J-16 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-17 Blue Canyon Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "September 24,2022 - October 30,2022",
      tagQuota: "25",
      tagValid: "Tag is valid for zone J-17 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-18 Pacific/Grizzly Flat Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "September 24,2022 - October 30,2022",
      tagQuota: "75",
      tagValid: "Tag is valid for zone J-18 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-19 Zone X-7a Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "25",
      tagValid: "Tag is valid for zone J-19 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-20 Zone X-7b Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "October 1,2022 - October 16,2022",
      tagQuota: "20",
      tagValid: "Tag is valid for zone J-20 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
    {
      name: "J-21 East Tehama Apprentice Either-Sex Deer Hunt",
      archery: "",
      general: "September 27,2022 - October 30,2022",
      tagQuota: "50",
      tagValid: "Tag is valid for zone J-21 only",
      requires:
        "Junior Hunting license, Deer tag, Must be accompanied by an adult 18 years of age or older while hunting",
    },
  ],

  bear: [
    {
      name: "Bear",
      archery: "August 20,2022 - September 11,2022 in all bear zones",
      general:
        "General bear season opens concurrently with general deer season in the A, B, C, D, X8, X9A, X9B, X10 and X12 deer hunting zones and extends through December 25, 2022. For those portions of zones X1, X2, X3a, X4, X6a, X6b, X7a, and X7b open to bear hunting, the general bear season begins October 8, 2022, and extends through December 25, 2022.",
      tagQuota:
        "General bear season closes on December 25, 2022, or earlier, if the Department determines that 1,700 bears have been reported taken. This includes bears harvested during the archery season.",
      tagValid: "Tag is valid for all zones open to bear hunting",
      requires: "bear tag, hunting license",
    },
  ],

  turkey: [
    {
      name: "Fall Turkey",
      archery: "November 12,2022 - December 11,2022",
      general: "November 12,2022 - December 11,2022",
      limitDay: "1 either sex, no beard needed",
      limitSeason: "2 per season, no beard needed",
      requires: "Upland game bird stamp,Hunting license",
    },
    {
      name: "Spring Turkey",
      archery: "May 1,2023 - May 14,2023",
      general: "March 25,2023 - April 30,2023",
      junior: "March 18 and 19,2023 also May 1,2023 - May 14,2023",
      limitDay: "1 bearded turkey",
      limitSeason: "3 per season",
      requires: "Upland game bird stamp,Hunting license",
    },
  ],

  dove: [
    {
      name: "First season of dove",
      season: "September 1,2023 - September 15,2023",
      limitDay: "15 total. Up to 10 of which may be white-winged doves",
      unlimited: "no limit on spotted dove and ringed turtle dove",
      possessionLimit: "3 times the daily bag limit",
      requires: "HIP validation, Upland game bird stamp,Hunting license",
    },
    {
      name: "Second season of dove",
      season: "November 12,2023 - December 26,2023",
      limitDay: "15 total. Up to 10 of which may be white-winged doves",
      unlimited: "no limit on spotted dove and ringed turtle dove",
      possessionLimit: "3 times the daily bag limit",
      requires: "HIP validation, Upland game bird stamp,Hunting license",
    },
    {
      name: "Eurasian Colllared Dove",
      season: "Open all year",
      limitDay: "no limits",
      requires: "HIP validation, Upland game bird stamp,Hunting license",
    },
  ],
};
